spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:singh12020428@gmail.com}
    password: ${MAIL_APP_PASSWORD:gbhl likv ygzy otbg}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          debug: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.zosh.event"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.zosh.event.BookingConfirmedEvent

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

notification:
  from-email: ${MAIL_FROM:singh12020428@gmail.com}
  from-name: "ZoshAir Notification"
  checkin-url: "Your frontend url"

server:
  port: 6000
